### ISSUE TITLE
UI suggestion: Admin drop down filter for refbacks

### ISSUE THREAD

**Issue by chrisaldrich** [dshanske/wordpress-refback#4]
Similar to the design set up for other comment types, it would be nice to have a filter for refbacks in the dropdown menu at `/wp-admin/edit-comments.php`.  With the Webmentions plugin enabled, one is presented with the options to filter for "All Comment Types", "Comments", "Pings", and "Webmentions". Adding a filter for "Refbacks" would be incredibly helpful as well.

![refback comment types dropdown](https://user-images.githubusercontent.com/5882943/50470933-71616300-0967-11e9-9afc-6c54ea786ea3.PNG)

(Originally published at https://boffosocko.com/2018/12/26/ui-suggestion-admin-drop-down-filter-for-refbacks/)

**Comment by dshanske** [comment]
Resolved in 2.0.
